### ISSUE TITLE
Assets not compiled on postinstall 

### ISSUE THREAD

**Issue by missingdink** [itsthatguy/generator-spire#18]
Had to add:    "postinstall": "$(npm bin)/bower install && $(npm bin)/gulp",

**Comment by itsthatguy** [comment]
I think there's a more developer friendly way to do this, instead of running these whenever you type `npm install` it should execute a script (or inline with this command) 
that checks to see if you're in [production or heroku] and if so, then run bower install and gulp

**Comment by itsthatguy** [comment]
`[[ $NODE_ENV = 'production' ]] && $(npm bin)/bower install && $(npm bin)/gulp`

**Comment by rylnd** [comment]
Where are you proposing that this lives?

**Comment by itsthatguy** [comment]
`postinstall` script in the `package.json` is fine
