### ISSUE TITLE
Config.sass tmp to src

### ISSUE THREAD

**Issue by missingdink** [itsthatguy/generator-spire#21]
in order for assets to compile, we needed to change the inject src from 

inject: {
    src: [path.join(config.PROJECT_ROOT, 'tmp/app/*_/_.scss')]

to

inject: {
    src: [path.join(config.PROJECT_ROOT, 'src/app/*_/_.scss')]

**Comment by itsthatguy** [comment]
@missingdink for changes like this, next time submit a PR ;)
